name: Django Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        run: |
          cd authentication/
          python manage.py migrate

      - name: Deploy to production
        run: |
          cd authentication/
          python manage.py runserver 0.0.0.0:8000
          echo "Deploying to production..."

# Agrega más trabajos según tus necesidades (ej. pruebas, despliegue a diferentes entornos, etc.)
